/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ProtocolProvenanceRegistry {
      
    export type ProtocolRecordStruct = {protocolName: string, contractAddress: AddressLike, version: string, auditHash: string, commitHash: string, auditor: string, timestamp: BigNumberish}

    export type ProtocolRecordStructOutput = [protocolName: string, contractAddress: string, version: string, auditHash: string, commitHash: string, auditor: string, timestamp: bigint] & {protocolName: string, contractAddress: string, version: string, auditHash: string, commitHash: string, auditor: string, timestamp: bigint }
  
    }

  export interface ProtocolProvenanceRegistryInterface extends Interface {
    getFunction(nameOrSignature: "getProtocolHistory" | "registerProtocolRecord"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ProtocolRegistered"): EventFragment;

    encodeFunctionData(functionFragment: 'getProtocolHistory', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'registerProtocolRecord', values: [string, AddressLike, string, string, string, string]): string;

    decodeFunctionResult(functionFragment: 'getProtocolHistory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerProtocolRecord', data: BytesLike): Result;
  }

  
    export namespace ProtocolRegisteredEvent {
      export type InputTuple = [contractAddress: AddressLike, version: string, auditHash: string, timestamp: BigNumberish];
      export type OutputTuple = [contractAddress: string, version: string, auditHash: string, timestamp: bigint];
      export interface OutputObject {contractAddress: string, version: string, auditHash: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ProtocolProvenanceRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): ProtocolProvenanceRegistry;
    waitForDeployment(): Promise<this>;

    interface: ProtocolProvenanceRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getProtocolHistory: TypedContractMethod<
      [contractAddress: AddressLike, ],
      [ProtocolProvenanceRegistry.ProtocolRecordStructOutput[]],
      'view'
    >
    

    
    registerProtocolRecord: TypedContractMethod<
      [protocolName: string, contractAddress: AddressLike, version: string, auditHash: string, commitHash: string, auditor: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getProtocolHistory'): TypedContractMethod<
      [contractAddress: AddressLike, ],
      [ProtocolProvenanceRegistry.ProtocolRecordStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'registerProtocolRecord'): TypedContractMethod<
      [protocolName: string, contractAddress: AddressLike, version: string, auditHash: string, commitHash: string, auditor: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ProtocolRegistered'): TypedContractEvent<ProtocolRegisteredEvent.InputTuple, ProtocolRegisteredEvent.OutputTuple, ProtocolRegisteredEvent.OutputObject>;

    filters: {
      
      'ProtocolRegistered(address,string,string,uint256)': TypedContractEvent<ProtocolRegisteredEvent.InputTuple, ProtocolRegisteredEvent.OutputTuple, ProtocolRegisteredEvent.OutputObject>;
      ProtocolRegistered: TypedContractEvent<ProtocolRegisteredEvent.InputTuple, ProtocolRegisteredEvent.OutputTuple, ProtocolRegisteredEvent.OutputObject>;
    
    };
  }