import { PDFDocument, StandardFonts } from "pdf-lib";

type CertificateData = {
    protocolName: string;
    contractAddress: string;
    version: string;
    auditor: string;
    auditHash: string;
    commitHash: string;
    txHash: string;
};

export async function generateCertificate(
    data: CertificateData
) {
    const pdfDoc = await PDFDocument.create();

    const page = pdfDoc.addPage([595, 842]);

    const font = await pdfDoc.embedFont(
        StandardFonts.Helvetica
    );

    const boldFont = await pdfDoc.embedFont(
        StandardFonts.HelveticaBold
    );

    let y = 780;

    page.drawText(
        "PROOFCHAIN REGISTRY CERTIFICATE",
        {
            x: 50,
            y,
            size: 22,
            font: boldFont,
        }
    );

    y -= 50;

    const lines = [
        `Protocol: ${data.protocolName}`,
        `Contract Address: ${data.contractAddress}`,
        `Version: ${data.version}`,
        `Auditor: ${data.auditor}`,
        "",
        "ON-CHAIN PROVENANCE",
        "",
        `Audit Hash: ${data.auditHash}`,
        `Commit Hash: ${data.commitHash}`,
        "",
        `Transaction Hash: ${data.txHash}`,
        "",
        `Generated: ${new Date().toLocaleString()}`,
        "",
        "This certificate was generated by ProofChain.",
        "Verification is performed by comparing the",
        "PDF hash against the immutable on-chain record.",
    ];

    for (const line of lines) {
        page.drawText(line, {
            x: 50,
            y,
            size: 11,
            font,
        });

        y -= 22;
    }

    const pdfBytes = await pdfDoc.save();

    const blob = new Blob(
        [pdfBytes.buffer as ArrayBuffer],
        { type: "application/pdf" }
    );

    const url = URL.createObjectURL(blob);

    const a = document.createElement("a");

    a.href = url;

    a.download =
        `proofchain-${data.protocolName
            .toLowerCase()
            .replace(/\s+/g, "-")}.pdf`;

    document.body.appendChild(a);

    a.click();

    document.body.removeChild(a);

    URL.revokeObjectURL(url);
}